### ISSUE TITLE
Attempt to invoke interface method 'java.util.HashMap 

### ISSUE THREAD

**Issue by yokei15** [code-computerlove/FastScrollRecyclerView#5]
java.lang.NullPointerException: Attempt to invoke interface method **'java.util.HashMap com.example.recyclerview.FastScrollRecyclerViewInterface.getMapIndex()' on a null object reference**
**at com.example.recyclerview.FastScrollRecyclerView.setupThings(FastScrollRecyclerView.java:59)
at com.example.recyclerview.FastScrollRecyclerView.onDraw(FastScrollRecyclerView.java:52)**
at android.view.View.draw(View.java:15635)
at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3171)
at android.view.View.draw(View.java:15544)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15638)
at android.view.View.draw(View.java:15544)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15638)
at android.widget.FrameLayout.draw(FrameLayout.java:598)
at android.view.View.draw(View.java:15544)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15542)
at android.view.ViewGroup.drawChild(ViewGroup.java:3604)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3397)
at android.view.View.draw(View.java:15638)
at android.widget.FrameLayout.draw(FrameLayout.java:598)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2945)
at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2689)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2602)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2385)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5930)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by midassimi** [comment]
How did you add the project to android studio?
